---
# contains the root directory for all OI files
root_path:  "C:/Users/adamt/Documents/Gaffney Lab/Tinsley_File_Structure/"

# contains the list of models to process
models:
  - data:
      name: AMCOI25
      residualLimbName: "femur_r"
      distalProstheticName: "walker_knee_r"
      outputFileName: "test_file_output.py"